/**
 * Pre-configured QR code templates for popular business & personal use cases.
 */

export const TEMPLATES = [
  {
    slug: 'restaurant-menu',
    title: 'Restaurant Contactless Menu',
    category: 'Restaurant',
    type: 'url',
    description: 'Instant contactless dining menu link designed for table stands and coasters.',
    accentColor: '#4F6EF7',
    pastelBg: '#EEF4FF',
    iconName: 'Utensils',
    defaultData: {
      url: 'https://example.com/menu',
    },
    customization: {
      fgColor: '#172033',
      bgColor: '#FFFFFF',
      ecc: 'H',
      size: 256,
    },
    useCases: [
      'Laminated table tents',
      'Bar coasters and counter stickers',
      'Outdoor patio dining stands',
    ],
    tips: 'Use High (H) error correction if menus are exposed to outdoor elements or food spills.',
  },
  {
    slug: 'wifi-guest-access',
    title: 'High-Speed Guest Wi-Fi',
    category: 'Hospitality',
    type: 'wifi',
    description: 'One-scan passwordless Wi-Fi connection card for guests, cafes, and offices.',
    accentColor: '#10B981',
    pastelBg: '#ECFDF3',
    iconName: 'Wifi',
    defaultData: {
      ssid: 'Guest-WiFi-5G',
      password: 'WelcomeToOurSpace2026',
      encryption: 'WPA',
      hidden: false,
    },
    customization: {
      fgColor: '#064E3B',
      bgColor: '#F0FDF4',
      ecc: 'M',
      size: 256,
    },
    useCases: [
      'Hotel room desks and lobby walls',
      'Coffee shop bulletin boards',
      'Conference meeting rooms',
    ],
    tips: 'Smartphones automatically recognize the WIFI: schema and prompt to join immediately.',
  },
  {
    slug: 'executive-business-card',
    title: 'Executive Digital vCard',
    category: 'Business',
    type: 'vcard',
    description: 'Direct address-book vCard contact card with instant "Save Contact" action.',
    accentColor: '#6366F1',
    pastelBg: '#EEF2FF',
    iconName: 'CreditCard',
    defaultData: {
      firstName: 'Sarah',
      lastName: 'Jenkins',
      organization: 'Acme Technologies',
      title: 'VP of Product Innovation',
      phone: '+1 555-019-2834',
      email: 'sarah.jenkins@example.com',
      url: 'https://sarahjenkins.design',
      address: '100 Market St, San Francisco, CA',
    },
    customization: {
      fgColor: '#312E81',
      bgColor: '#FFFFFF',
      ecc: 'Q',
      size: 288,
    },
    useCases: [
      'Backside of printed business cards',
      'Conference badge name tags',
      'Email signatures and presentation end slides',
    ],
    tips: 'vCards pack dense data; keep the printed size at least 1.5 x 1.5 inches for clean scanning.',
  },
  {
    slug: 'whatsapp-direct-chat',
    title: 'WhatsApp Instant Support',
    category: 'Marketing',
    type: 'whatsapp',
    description: 'Pre-filled customer support or sales chat link directly into WhatsApp.',
    accentColor: '#22C55E',
    pastelBg: '#F0FDF4',
    iconName: 'MessageSquare',
    defaultData: {
      phone: '+1 555 014 9823',
      message: 'Hi! I would like to inquire about your product catalog.',
    },
    customization: {
      fgColor: '#14532D',
      bgColor: '#FFFFFF',
      ecc: 'M',
      size: 256,
    },
    useCases: [
      'Product packaging and unboxing cards',
      'Storefront customer support stickers',
      'Print advertisements & catalogs',
    ],
    tips: 'Pre-populating a greeting message increases chat conversion rates by over 40%.',
  },
  {
    slug: 'social-media-hub',
    title: 'Instagram & Social Growth',
    category: 'Social',
    type: 'social',
    description: 'Quick follower conversion link for Instagram, TikTok, YouTube, or LinkedIn.',
    accentColor: '#EC4899',
    pastelBg: '#FFF1F7',
    iconName: 'Share2',
    defaultData: {
      platform: 'instagram',
      url: 'https://instagram.com/mybrand',
    },
    customization: {
      fgColor: '#831843',
      bgColor: '#FFFFFF',
      ecc: 'Q',
      size: 256,
    },
    useCases: [
      'Retail checkout counter signs',
      'Event booth banners and backdrops',
      'Shopping bags and receipt footers',
    ],
    tips: 'Pair with an incentive like "Tag us for 10% off your next purchase!"',
  },
  {
    slug: 'google-maps-storefront',
    title: 'Google Maps Store Pin',
    category: 'Local Business',
    type: 'maps',
    description: 'Direct navigation link launching GPS directions to your physical venue.',
    accentColor: '#F97316',
    pastelBg: '#FFF7ED',
    iconName: 'MapPin',
    defaultData: {
      address: '742 Evergreen Terrace, Springfield, OR',
    },
    customization: {
      fgColor: '#7C2D12',
      bgColor: '#FFFFFF',
      ecc: 'M',
      size: 256,
    },
    useCases: [
      'Event flyers and wedding invitations',
      'Local magazine print advertisements',
      'Directional outdoor signage',
    ],
    tips: 'Works seamlessly with Google Maps, Apple Maps, and browser navigation.',
  },
  {
    slug: 'conference-event-pass',
    title: 'Calendar Event Reminder',
    category: 'Events',
    type: 'event',
    description: 'One-tap calendar addition for keynotes, webinars, workshops, or weddings.',
    accentColor: '#8B5CF6',
    pastelBg: '#F5F3FF',
    iconName: 'Calendar',
    defaultData: {
      title: 'Global Tech Summit 2026',
      location: 'Moscone Center, SF',
      startDate: '2026-10-15T09:00',
      endDate: '2026-10-15T18:00',
      notes: 'Keynote starts promptly at 9:30 AM in Main Hall A.',
    },
    customization: {
      fgColor: '#4C1D95',
      bgColor: '#FFFFFF',
      ecc: 'M',
      size: 256,
    },
    useCases: [
      'Save-the-date cards and invitations',
      'Conference schedules and attendee guides',
      'Tickets and registration confirmations',
    ],
    tips: 'Eliminates missed meetings by directly adding timezone-aware alerts to Apple/Google calendars.',
  },
  {
    slug: 'crypto-payment-wallet',
    title: 'Crypto Tip Jar & Payment',
    category: 'Finance',
    type: 'crypto',
    description: 'Instant mobile cryptocurrency payment address for tips or invoices.',
    accentColor: '#F59E0B',
    pastelBg: '#FEF3C7',
    iconName: 'Coins',
    defaultData: {
      coin: 'BTC',
      address: 'bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',
      amount: '0.005',
    },
    customization: {
      fgColor: '#78350F',
      bgColor: '#FFFFFF',
      ecc: 'H',
      size: 288,
    },
    useCases: [
      'Creator tip jars on streams and blogs',
      'Physical artisan pop-up booth checkout',
      'Invoice PDFs and merchant receipts',
    ],
    tips: 'High (H) error correction ensures payment addresses remain 100% scannable even when worn.',
  },
  {
    slug: 'secret-encrypted-note',
    title: 'Password-Protected Secret Note',
    category: 'Security',
    type: 'text',
    description: 'Zero-knowledge AES-256 encrypted note that unlocks only with the secret passcode.',
    accentColor: '#D97706',
    pastelBg: '#FFFBEB',
    iconName: 'Lock',
    defaultData: {
      title: 'Confidential Wi-Fi & Access Codes',
      text: 'Server room passcode is 9876. Wi-Fi master key: SecretStudio2026!',
      isProtected: true,
      password: 'Pass',
    },
    customization: {
      fgColor: '#78350F',
      bgColor: '#FFFFFF',
      ecc: 'M',
      size: 256,
    },
    useCases: [
      'Private security credentials & passwords',
      'Confidential meeting notes & access codes',
      'Surprise messages and scavenger hunts',
    ],
    tips: 'Opens on QRHub Secret Vault where recipients enter the passcode to decrypt locally on their device.',
  },
  {
    slug: 'bulk-batch-table-stickers',
    title: 'Bulk Table & Asset Stickers',
    category: 'Operations',
    type: 'bulk',
    description: 'Mass-generate sequential numbered QR codes for restaurant tables, warehouse assets, or tickets.',
    accentColor: '#2563EB',
    pastelBg: '#EFF6FF',
    iconName: 'Layers',
    defaultData: {
      url: '/bulk',
    },
    customization: {
      fgColor: '#1E40AF',
      bgColor: '#FFFFFF',
      ecc: 'H',
      size: 256,
    },
    useCases: [
      'Restaurant table ordering stands (Table 1 to 50)',
      'Warehouse bin and pallet tracking codes',
      'Conference attendee badge QR series',
    ],
    tips: 'Use the Sequence Builder in Bulk Studio to generate dozens of numbered codes in 1 click.',
  },
];
